# Site settings
title: Jen Haines
email: jen@jenhaines.com
url: http://www.jenhaines.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "Full Stack Developer - Frontend - User Experience Designer"
meta_author: Haines Jen

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

theme:
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Jen C. Haines
  location: Earth
  social: Around the Web
  credits: Thank You

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jenchaines
  - title: linkedin
    url: https://www.linkedin.com/in/jenhaines
  - title: google-plus
    url: https://plus.google.com/+JenniferHaines46
  - title: github
    url: http://github.com/jenhaines
  - title: facebook
    url: https://www.facebook.com/jane6767

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# COLLECTIONS
collections:
  portfolio:
    output: true

# GEMS
gems: [jekyll-paginate, pygments.rb, redcarpet]
paginate: 5
paginate_path: "blog/page:num"

# Credits content
credits: '<a href="https://jekyllrb.com">Jekyll</a> and <a href="http://startbootstrap.com">Start Bootstrap</a> for helping me create this site.'

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
